<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQX9lRSr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQX9lRSr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQX9lRSr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQX9lRSr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQX9lRSr\App_KernelDevDebugContainer([
    'container.build_hash' => 'QX9lRSr',
    'container.build_id' => 'c300004f',
    'container.build_time' => 1731323567,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQX9lRSr');
