<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDXSbJs1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDXSbJs1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDXSbJs1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDXSbJs1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDXSbJs1\App_KernelDevDebugContainer([
    'container.build_hash' => 'DXSbJs1',
    'container.build_id' => '32d3690d',
    'container.build_time' => 1731323058,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDXSbJs1');
